---
title: "EqitableEquations_gt"
format: html
---

```{r}
#| label: setup
#| message: false

library(gt)
library(tidyverse)
library(modeldata)
```

```{r}
#| label: preprocessing

scat_table1 <- scat |> 
  select(Species,
         Site,
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) |> 
  group_by(Species) |> 
  summarise(across(where(is.numeric),
                   \(x) round(mean(x, na.rm = TRUE), 1)),
            count = n(), .groups = "drop")

scat_table2 <- scat |> 
  select(Species,
         Location,
         Site,
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) |> 
  group_by(Species, Site) |> 
  summarise(across(where(is.numeric),
                   \(x) round(mean(x, na.rm = TRUE), 1)),
            count = n(), .groups = "drop")
```

## A great table

```{r}
#| label: first_table

scat_table1 |> 
  gt(rowname_col = "Species") |> 
  cols_label(count = md("**Count**")) |> 
  tab_header(title = "California poopies", 
             subtitle = "Morphometric data on scat") |> 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015). A morphometric modeling approach to distinguishing among bobcat, coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) |> 
  tab_spanner(label = "Physical averages", columns = Length:Mass) |> 
  tab_stubhead(label = "Species")
```

## A stylized version

```{r}
#| label: second_table

scat_table1 |> 
  gt() |> 
  cols_label(count = md("**Count**")) |> 
  tab_header(title = "California poopies", 
             subtitle = "Morphometric data on scat") |> 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015). A morphometric modeling approach to distinguishing among bobcat, coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) |> 
  tab_spanner(label = "Physical averages", columns = Length:Mass) |> 
  opt_stylize(style = 2, color = "blue")
```

## Grouped data

```{r}
scat_table2 |> 
  gt(groupname_col = "Species")
```






